version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias..."
      - pip install -r requirements.txt

artifacts:
  files:
    - '**/*'
