version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "[Install Phase] Instalando dependencias..."
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo "[Pre-Build Phase] Estructura de archivos:"
      - ls -R
      - echo "[Pre-Build Phase] Ejecutando pruebas unitarias..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests/
  build:
    commands:
      - echo "[Build Phase] Copiando archivos de blacklist_service/"
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
artifacts:
  files:
    - '**/*'

