version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "[Install Phase] Instalando dependencias..."
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo "[Pre-Build Phase] Estructura de archivos:"
      - ls -R
      - echo "[Pre-Build Phase] Ejecutando pruebas unitarias..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests/
  build:
    commands:
      - echo "[Build Phase] Empaquetando aplicación para Elastic Beanstalk..."
      #- zip -r app.zip * .ebextensions -x "*.DS_Store" "__MACOSX/*"
      - echo "[Build Phase] Archivo app.zip generado correctamente."
artifacts:
  files:
    - '**/*'
  discard-paths: yes

