version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest tests/

  build:
    commands:
      - echo "Copiando archivo principal al root (por seguridad)..."
      - cp application.py ./application.py
      - echo "Empaquetando aplicación..."
      - zip -r app_package.zip . -x "*.git*" "tests/*" "*.venv*" "__pycache__/*" "*.DS_Store"

artifacts:
  files:
    - app_package.zip
