version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias para testing..."
      - cd blacklist_service
      - pip install --upgrade pip
      - pip install -r requirements.txt --verbose

  build:
    commands:
      - echo "✅ Ejecutando pruebas..."
      - cd blacklist_service
      - pytest tests/ --maxfail=1 --disable-warnings --tb=short > result.log || true

artifacts:
  files:
    - '**/*'
    - result.log
