version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest -v --tb=short tests/


  build:
    commands:
      - echo "Construyendo el archivo ZIP con Dockerrun.aws.json..."
      - ls -la
      - echo "Fase de build completa"
  
  post_build:
  commands:
    - echo "Generando imagedefinitions.json..."
    - printf '[{"name":"microservicio","imageUri":"%s"}]' $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json




artifacts:
  files:
    - taskdef.json
    - appspec.json
    - imagedefinitions.json
  discard-paths: no

