version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Instalando dependencias...
      - pip install -r blacklist_service/requirements.txt
      - pip install pytest faker

  pre_build:
    commands:
      - echo Ejecutando pruebas unitarias...
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist_service
      - pytest tests/

  build:
    commands:
      - echo Construcción completada exitosamente.
      - echo Construyendo imagen Docker...
      - docker build -t mi-microservicio -f blacklist_service/Dockerfile blacklist_service

  post_build:
    commands:
      - echo Fase post_build finalizada.

artifacts:
  files:
    - '**/*'