version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests/

  build:
    commands:
      - echo "Empaquetando aplicación..."
      - zip -r app.zip . -x '*.git*' '*.DS_Store*' '*__MACOSX*' "*.venv*"

artifacts:
  files:
    - app.zip

