version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest tests/

  build:
    commands:
      - echo "Empaquetando aplicación..."
      - zip -r app-deploy.zip app application.py requirements.txt Procfile config.py entrypoint.sh \
        -x "*.pyc" "*__pycache__*" ".venv/*" ".DS_Store"

artifacts:
  files:
    - app-deploy.zip

