version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "[Install Phase] Instalando dependencias..."
      - pip install -r blacklist_service/requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo "[Pre-Build Phase] Ejecutando pruebas unitarias..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/blacklist_service
      - pytest blacklist_service/tests/
  build:
    commands:
      - echo "[Build Phase] Copiando archivos de blacklist_service/"
      - cp -r blacklist_service/* .
artifacts:
  files:
    - '**/*'
  discard-paths: yes
