version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 646322278084.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mi-microservicio .
      - docker tag mi-microservicio:latest 646322278084.dkr.ecr.us-east-2.amazonaws.com/mi-microservicio:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 646322278084.dkr.ecr.us-east-2.amazonaws.com/mi-microservicio:latest
      - echo Writing image definitions file...
      - printf '[{"name":"microservicio","imageUri":"646322278084.dkr.ecr.us-east-2.amazonaws.com/mi-microservicio:latest"}]' > imagedefinitions.json
      - echo Writing appspec \& taskdef
      - cat appspec.json
      - cat taskdef.json
      - echo Writing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - appspec.json
    - taskdef.json
    - imagedefinitions.json
  discard-paths: no
