version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest tests/

  build:
    commands:
      - mkdir app_bundle
      - rsync -av --progress ./ ./app_bundle --exclude='.git' --exclude='*.DS_Store' --exclude='__MACOSX'
      - cd app_bundle
      - zip -r ../app.zip .

artifacts:
  files:
    - app.zip

