version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest tests/ || echo "Las pruebas fallaron pero el proceso continúa"

  build:
    commands:
      - echo "Generando archivo ZIP del contenido del repositorio..."
      - zip -r app_package.zip . -x "*.git*" "tests/*" "*.venv*" "__pycache__/*" "*.DS_Store"

artifacts:
  files:
    - app_package.zip
