version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest -v --tb=short tests/


  build:
    commands:
      - echo "Construyendo el archivo ZIP con Dockerrun.aws.json..."
      - zip app-deploy.zip Dockerrun.aws.json


artifacts:
  files:
    - app-deploy.zip
  discard-paths: yes

