version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas (opcional)..."
      - pytest tests/

  build:
    commands:
      - echo "Empaquetando aplicación..."
      - mkdir packaged
      - cp application.py config.py entrypoint.sh Procfile requirements.txt packaged/
      - cp -r app packaged/
      - cd packaged
      - zip -r ../app-deploy.zip . -x "*.pyc" "*__pycache__*" "*.DS_Store" ".venv/*"


artifacts:
  files:
    - app-deploy.zip

