version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Instalando dependencias...
      - pip install -r blacklist_service/requirements.txt
      - pip install pytest faker
  pre_build:
    commands:
      - echo Ejecutando pruebas unitarias...
      - cd blacklist_service
      - pytest ../tests/
  build:
    commands:
      - echo Construcción completada exitosamente.
  post_build:
    commands:
      - echo Fase post_build finalizada.

artifacts:
  files:
    - '**/*'
