version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias..."
      - cd blacklist_service
      - pip install --upgrade pip
      - pip install -r requirements.txt --verbose

  build:
    commands:
      - echo "✅ Build completado. Preparando artefactos para despliegue..."
      - pytest blacklist_service/tests/ --maxfail=1 --disable-warnings --tb=short > result.log

artifacts:
  base-directory: 'blacklist_service'
  files:
    - '**/*'
    - ../result.log
